version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: novel-web
    restart: always
    ports:
      - "3000:3000"
    extra_hosts:
      # Mengizinkan container Docker menghubungi host server menggunakan host.docker.internal
      - "host.docker.internal:host-gateway"
    environment:
      # Koneksi database diarahkan ke MariaDB bawaan server host menggunakan host.docker.internal
      - DATABASE_URL=mysql://root:Hantu@123@host.docker.internal:3306/novel
      - AUTH_SECRET=q0gQCtl5jAaGH2Bv2F25P4XUlW/uHLLv47d+AhN6fUGY=
      - ADMIN_STUDIO_TOKEN=Ad4zadyTHzxSkMG58kwWuorSvucKiiGRWfUFscaISB4uVfec493YO7Wk4LkqO1MR
